package model.enums;

public enum Action {
    USER_CREATED,
    USER_UPDATED,
    USER_DELETED,
    RESERVATION_CREATED,
    RESERVATION_UPDATED,
    RESERVATION_DELETED,
    WORKSPACE_CREATED,
    WORKSPACE_UPDATED,
    WORKSPACE_DELETED
}
